import os

ENV = os.getenv("ENV", "development")

BACKEND_DB_HOST = os.getenv("BACKEND_DB_HOST")
BACKEND_DB_USER = os.getenv("BACKEND_DB_USER")
BACKEND_DB_NAME = os.getenv("BACKEND_DB_NAME")
BACKEND_DB_PASSWORD = os.getenv("BACKEND_DB_PASSWORD")
BACKEND_DB_PORT = os.getenv("BACKEND_DB_PORT")
BACKEND_DB_DIALECT = os.getenv("BACKEND_DB_DIALECT")
BACKEND_DB_DRIVER = os.getenv("BACKEND_DB_DRIVER")
PFG_WATCHER_POSTGRES_URL = os.getenv("PFG_WATCHER_POSTGRES_URL")
PFG_WATCHER_POSTGRES_TABLENAME = os.getenv("PFG_WATCHER_POSTGRES_TABLENAME")
